config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  get 'test' => 'microposts#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  resources :microposts, only: [:create, :destroy]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def feed
    Micropost.where("user_id = ?", id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  
  private
  
    def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost = current_user.microposts.find(params[:id])
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  
  def new
    @user= User.new
    @contact = Contact.new
  end
  
  def create
    @user = User.new
    @user.username = params[:user][:username]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation =params[:user][:password_confirmation]

    @contact = Contact.new
    @contact.mobile = params[:contact][:mobile]
    @contact.address = params[:contact][:address]
    @member.valid?
  
    if @user.errors.blank?
      @user.save
      @contact.user = @user
      @contact.save
      redirect_to dashboard_path
    else
      render :action => "new"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index,:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
  
   private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user
    if(user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def current_user?(user)
    user == current_user
  end
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/home/dashboard.html.erb
<p>hi welcome to Ruby community. you have successfully registered to your rails club account</p>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/home/index.html.erb
<% if user_signed_in? %>

<h3>you have succesfully signed in</h3>
<%= link_to "Sign Out", destroy_userer_session_path, :method => :delete %>

<% else %>

<h1> welcom to rails community</h1>
<%= link_to "Sign In", new_user_session_path, :method => :get %>
<%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>

app/views/layouts/_footer.html.haml
%footer
    %small
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    %nav
        %ul
            %li 
                = link_to "About", about_path 
            %li 
                = link_to "Contact", contact_path 
            %li 
                = link_to "News", "http://news.railstutorial.org/"

app/views/layouts/_header.html.haml
%header{:class => "navbar navbar-fixed-top navbar-inverse"}
    .container
        = link_to "sample app", root_path , id: "logo"
        .nav
            %ul{:class => "nav navbar-nav navbar-right"} 
                %li 
                    =link_to "Home",   root_path
                %li 
                    =link_to "Help",   help_path
                -if logged_in?
                    %li 
                        = link_to "Users", users_path
                    %li.dropdown
                        %a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#"}
                            Account 
                            %b.caret
                        %ul.dropdown-menu{"role" => "menu"}
                            %li
                                = link_to "Profile", current_user
                            %li
                                = link_to "Settings", edit_user_path(current_user) 
                            %li{:class=>"divider"}
                            %li
                                = link_to "Log out", logout_path, method: "delete"
                -else     
                    %li 
                        =link_to "Log in", login_path

app/views/layouts/_shim.html.haml
<!--[if !IE]> -->
%script{:src  =>  "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"}
<!-- <![endif]-->

app/views/layouts/application.html.haml
%html
  %head
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      -flash.each do |message_type, message| 
        %div{:class => "alert alert-#{message_type}"}
          = message
      = yield
      = render 'layouts/footer'

app/views/microposts/_micropost.html.haml
%li{:id=>"micropost-#{micropost.id}"}
  = link_to gravatar_for(micropost.user, size: 50), micropost.user
  %span{:class=>"user"}
    = link_to micropost.user.name, micropost.user
  %span{:class=>"content"}
    = micropost.content
  %span{:class=>"timestamp"}
    Posted = #{time_ago_in_words(micropost.created_at)} ago.
    -if current_user?(micropost.user) 
      = link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" }

app/views/microposts/new.html.haml
=provide(:title, 'New Post')
%h1
  New post
%div{ :class=>"row"}
  %div{ :class=>"col-md-6 col-md-offset-3"}
  -form_for Micropost.new do |f| 
    = render 'shared/error_messages', object: f.object 
    %div{:class=>"field"}
      = f.text_area :content, placeholder: "Compose new micropost..." 
    = f.submit "Post", class: "btn btn-primary"

app/views/shared/_error_messages.html.haml
-if object.errors.any?
  %div{:id=>"error_explanation"}
    %div{ :class=>"alert alert-danger"}
      The form contains 
      = pluralize(object.errors.count, "error")
    %ul
      - object.errors.full_messages.each do |msg| 
        %li
          = msg

app/views/shared/_feed.html.haml
-if @feed_items.any? 
  %ol{:class=>"microposts"}
    = render @feed_items 
  = will_paginate @feed_items 

app/views/shared/_micropost_form.html.haml
=form_for(@micropost) do |f| 
  = render 'shared/error_messages', object: f.object 
  %div{:class=>"field"}
    = f.text_area :content, placeholder: "Compose new micropost..." 
  = f.submit "Post", class: "btn btn-primary"

app/views/shared/_user_info.html.haml
= link_to gravatar_for(current_user, size: 50), current_user
%h1
  = current_user.name
%span
  = link_to "view my profile", current_user
%span
  = pluralize(current_user.microposts.count, "micropost")

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/about.html.haml
=provide(:title, "About") 
%h1 About
%p
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.

app/views/static_pages/contact.html.haml
=provide(:title, 'Contact')
%h1
  Contact
%p
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/help.html.haml
=provide(:title, "Help")
%h1 Help
%p
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.

app/views/static_pages/home.html.haml
-if logged_in? 
  %div{:class=>"row"}
    %aside{:class=>"col-md-4"}
      %section{:class=>"user_info"}
        = render 'shared/user_info' 
      %section{:class=>"micropost_form"}
        = render 'shared/micropost_form'
    %div{:class=>"col-md-8"}
      %h3
        Micropost Feed
      = render 'shared/feed'
-else
  .center.jumbotron
    %h1 
      Welcome to the Sample App
    %h2
      This is the home page for the 
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    =link_to "Sign up now!", signup_path , {:class => "btn btn-lg btn-primary"}
  = link_to image_tag('rails.png', alt: 'Rails logo'), 'http://rubyonrails.org/' 

app/views/users/_user.html.haml
%li
  = gravatar_for user, size: 50 
  = link_to user.name, user 

app/views/users/_user_form.html.haml
=form_for(@user) do |f|
  = render 'shared/error_messages', object: f.object
  = f.label :name 
  = f.text_field :name, class: 'form-control'
  

  = f.label :email 
  = f.email_field :email, class: 'form-control' 

  = f.label :password 
  = f.password_field :password, class: 'form-control' 

  = f.label :password_confirmation, "Confirmation" 
  = f.password_field :password_confirmation, class: 'form-control' 
  
  = f.submit "Submit", class: "btn btn-primary" 

app/views/users/edit.html.haml
=provide(:title, "Edit user")
%h1
  Update your profile
%div{ :class=>"row"}
  %div{ :class=>"col-md-6 col-md-offset-3"}
    %div{:class=>"gravatar_edit"}
      = render'user_form'
      = gravatar_for @user 
      = link_to 'Change', "http://gravatar.com/emails", target:"_blank"
      

app/views/users/index.html.haml
=provide(:title, 'All users')
%h1 All users

= will_paginate

%ul{:class=>"users"}
    = render  @users
    
= will_paginate

app/views/users/new.html.haml
=provide(:title, 'Sign up')
%h1
  Sign up
%div{ :class=>"row"}
  %div{ :class=>"col-md-6 col-md-offset-3"}
    = render 'user_form'

app/views/users/show.html.haml
=provide(:title, @user.name)
%div{:class=>"row"}
  %aside{:class=>"col-md-4"}
    %section{:class=>"user_info"}
      %h1
        = gravatar_for @user 
        = @user.name
  %div{:class=>"col-md-8"}
    -if @user.microposts.any?
      %h3
        Microposts (#{@user.microposts.count})
      %ol{:class=>"microposts"}
        = render @microposts 
      = will_paginate @microposts